baseURL = "http://example.org/"
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
title = "New onepage site"
[hero]
background_color = "#97D0B4"
subtitle = "rqsdfqsdfqsf"
title = "azerazer"
[markup.goldmark.renderer]
unsafe = true
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
logo = "images/logo.png"
logo_width = "200px"
[[params.plugins.css]]
link = "plugins/css/bulma.css"
[[params.plugins.css]]
link = "plugins/css/custom.css"
[[params.plugins.css]]
link = "plugins/css/fontello.css"
[[params.plugins.js]]
link = "plugins/js/main.js"
